### ISSUE TITLE
计算最终预测值时，公式有些疑惑

### ISSUE THREAD

**Issue by JoyceCoder** [Maple728/DA-RNN#1]
https://github.com/Maple728/DA-RNN/blob/a3cdb99eb64eb310c6a78cd7e96b6330f95b12fc/DA_RNN.py#L159

计算最终预测值时，论文中给出的方法是对解码器的隐状态和context_vector进行concatenation。您的代码中是X_encoders，是我哪里理解错了吗？

**Comment by Maple728** [comment]
你说的对，的确是与context_vector进行concatenation。
