### ISSUE TITLE
Train, Valid, Test Split

### ISSUE THREAD

**Issue by guney1** [Maple728/DA-RNN#2]
Hi Great work thank you. 

I wanted to ask you the reason why you including last 10 points of train set to valid set also last 10 points of valid set to test set? Is there a specific reason why are you doing like that?

I am referring to here:
return dataset[ :,  : train_end_index], dataset[:,  train_end_index - config.timestep : valid_end_index], dataset[:, valid_end_index - config.timestep : -1]

Thanks a lot

**Comment by Maple728** [comment]
Hi, 

I did it for using more data and maintaining a fixed test set length in different timesteps. It's okay not use the last 10 points in your experiment.

**Comment by guney1** [comment]
Thank you so much for the quick response.
